### ISSUE TITLE
Event names are lowercase instead of camelCase

### ISSUE THREAD

**Issue by MaxBen93** [microsoft/react-native-winrt#229]
We discovered that when attempting to register for an event on a WinRT object, if that event name was originally comprised of multiple words (in PascalCase), the generated code would make it entirely lowercase instead of being camelCase as is done elsewhere.

A simple example of this is to build the sample app as-is, then look at `\samples\RNWinRTTestApp\windows\WinRTTurboModule\Generated Files\rnwinrt\Windows.UI.StartScreen.g.cpp` and search for `VisualElementsRequested`.  You will see that in the generated code makes it such that an all lowercase string is expected to be used when registering for this event (using camelCase results in the event appearing to not be triggered on the JS side without much in the way of logging/warning).

```cpp
static constexpr const static_interface_data::event_mapping event_data[] = {
>>> { "visualelementsrequested",
        [](jsi::Runtime& runtime, const winrt::Windows::Foundation::IInspectable& thisValue, const jsi::Value& callback) {
            return thisValue.as<winrt::Windows::UI::StartScreen::ISecondaryTile2>().VisualElementsRequested(convert_value_to_native<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::UI::StartScreen::SecondaryTile, winrt::Windows::UI::StartScreen::VisualElementsRequestedEventArgs>>(runtime, callback));
        },
        [](const winrt::Windows::Foundation::IInspectable& thisValue, winrt::event_token token) {
            thisValue.as<winrt::Windows::UI::StartScreen::ISecondaryTile2>().VisualElementsRequested(token);
        }
    },
```

**Comment by dunhor** [comment]
@nichamp may be able to give more context, but this was done by design. It follows JS event naming conventions (`"pointerdown"`, `"keydown"`, `"visibilitychange"`, etc.) as well as the Win8 Chakra behavior (e.g. [here](https://github.com/microsoft/Windows-universal-samples/blob/b1cb20f191d3fd99ce89df50c5b7d1a6e2382c01/archived/ShareSource/js/js/applicationlink.js#L8), [here](https://github.com/microsoft/Windows-universal-samples/blob/b1cb20f191d3fd99ce89df50c5b7d1a6e2382c01/archived/Printing/js/js/scenario1basic.js#L28), [here](https://github.com/microsoft/Windows-universal-samples/blob/b1cb20f191d3fd99ce89df50c5b7d1a6e2382c01/Samples/WRLInProcessWinRTComponent/cpp/js/js/scenario1-oven-client.js#L22), etc.)

**Comment by dunhor** [comment]
The no error follows JS convention (e.g. `document.addEventListener('thiseventdoesnotexist', () => {})` does not throw/error). This is also the behavior when accessing an invalid property (we return `undefined` instead of throwing). Personally I'm not opposed to throwing in this scenario, but there is something to be said about the consistency of it

**Comment by MaxBen93** [comment]
Thanks for the quick reply, @dunhor !

I suppose this appeared a bit odd to me (without that context) because the properties and methods are projected using camelCase so it felt like a bug.  That context is super helpful though :)
