### ISSUE TITLE
RNW v0.75.4 & RN-WINRT v0.72.1 No Longer Builds

### ISSUE THREAD

**Issue by KGGrande** [microsoft/react-native-winrt#298]
### The Problem:
Originally, I had a solution with this exact setup that was working. I then removed some bloat from Visual Studio 2019 and 2022 that as far as I know should not affect react-native-winrt. I have the required dependencies outlined on the docs with the addition of 10.0.18362 through visual studio 2022 as requested by react-native-winrt. 

### Steps to Reproduce:
`yarn add react-native-windows@^0.75.4`
`yarn react-native init-windows --overwrite`
`yarn react-native run-windows`
Builds with no issue.
Stop debug session.
`yarn add react-native-winrt`
`yarn react-native run-windows`

### Error
`C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(482,5): error MSB4181: The "CompileXaml" task returned false but did not log an error. [C:\Users\source\repos\projects\ExampleApp\node_modules\react-native-winrt\windows\WinRTTurboModule\WinRTTurboModule.vcxproj]`

and

`C:\Users\source\repos\projects\ExampleApp\node_modules\react-native-winrt\windows\WinRTTurboModule\Generated Files\rnwinrt\base.h(3034,113): error C3878: syntax error: unexpected token '<' following 'simple-type-specifier' [C:\Users\source\repos\projects\ExampleApp\node_modules\react-native-winrt\windows\WinRTTurboModule\WinRTTurboModule.vcxproj]`

### Question
What are the requirements for react-native-winrt to build properly?

**Comment by LyDawei** [comment]
I'm having the same problem.

**Comment by dunhor** [comment]
Thanks for reporting. This is because of `IVectorChangedEventArgs` being treated as a template on the offending line, even though that type is not a template. I guess older versions of MSVC were more permissive here & didn't raise an error if the containing template was never instantiated.

The good news is this is an easy fix. The bad news is ownership of this repo has changed hands at least twice in the last few years and I'm not yet sure who's responsible for it at the moment. What I'll do is I'll submit a quick fix & update the latest version on npm. The nuget package as well as bumping the version will probably have to wait. Some Visual Studio and/or msbuild update broke the tests and I'd wager that the pipeline that produces the nuget package has broken in that time frame as well. Those are likely to be non-trivial to fix and I unfortunately don't have the time to investigate them at the moment

**Comment by dunhor** [comment]
Just published
